services:
  postgres:
    image: postgres:16
    container_name: 'postgres'
    restart: always
    ports:
      - 5732:5432
    environment:
      - POSTGRES_PASSWORD=fast
      - POSTGRES_DB=fast

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5772:5672
      - 15772:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

  producer:
    depends_on:
      - postgres
      - rabbitmq
    build: ./producer/
    container_name: 'producer'
    ports:
      - 8000:8000
